### ISSUE TITLE
openapi.yaml is parsed as if it was a JSON

### ISSUE THREAD

**Issue by TamasBarta** [gibahjoe/openapi-generator-dart#65]
I went through setting up the project, and tried to run the generator on a YAML file we have, and I get a bunch of JSON errors: 

```
[INFO] Generating build script...
[INFO] Generating build script completed, took 325ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 59ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 672ms

[INFO] Running build...
[INFO] 1.1s elapsed, 0/1 actions completed.
[INFO] 2.1s elapsed, 0/1 actions completed.
[INFO] 10.6s elapsed, 0/1 actions completed.
[WARNING] openapi_generator:openapi_generator on lib/app/app.dart:
OpenapiGenerator :: [generate -i openapi/openapi.yaml -g dart -o something_api --additional-properties=pubName=someting_api,pubAuthor=Tamás Barta]
[WARNING] openapi_generator:openapi_generator on lib/app/app.dart:
------------------------------------------------------
|                                                     |
|             Openapi generator for dart              |
|                                                     |
|                                                     |
------------------------------------------------------
[WARNING] openapi_generator:openapi_generator on lib/app/app.dart:
Executing command [generate -i openapi/openapi.yaml -g dart -o something_api --additional-properties=pubName=something_api,pubAuthor=Tamás Barta]
[WARNING] openapi_generator:openapi_generator on lib/app/app.dart:
Picked up _JAVA_OPTIONS: -Djava.util.prefs.userRoot=/home/tamas/.config/java
[main] ERROR i.s.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
 at [Source: (String)"---
openapi: 3.1.0
...
"[truncated 3791 chars]; line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserMinimalBase.reportUnexpectedNumberChar(ParserMinimalBase.java:541)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleInvalidNumberStart(ReaderBasedJsonParser.java:1652)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseNegNumber(ReaderBasedJsonParser.java:1406)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:758)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:210)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
	at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:94)
	at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:44)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:89)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:523)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
[main] ERROR i.s.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
 at [Source: (String)"---
openapi: 3.1.0
...
"[truncated 3791 chars]; line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserMinimalBase.reportUnexpectedNumberChar(ParserMinimalBase.java:541)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleInvalidNumberStart(ReaderBasedJsonParser.java:1652)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseNegNumber(ReaderBasedJsonParser.java:1406)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:758)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:210)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
	at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:94)
	at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:44)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:89)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:523)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Exception in thread "main" java.lang.RuntimeException: Issues with the OpenAPI input. Possible causes: invalid/missing spec, malformed JSON/YAML files, etc.
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:861)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

[WARNING] openapi_generator:openapi_generator on lib/app/app.dart:
OpenapiGenerator :: Codegen Failed
[INFO] Running build completed, took 11.5s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 40ms

[INFO] Succeeded after 11.6s with 0 outputs (1 actions)
```

The original error messages contained almost the complete YAML, so I replaced those parts with "...".

The YAML file is recognized by other tools, it is formatted properly, but according to the error messages it is parsed as if it was a JSON file.

I added the `---` at the beginning of the YAML, because I saw that in the examples, and I thought it may help with recognizing it as a JSON, but neither version works.

**Comment by TamasBarta** [comment]
I found a workaround:

Specify the `openapi` version as `3.0.0`, because it checks for that instead of filename, or whatever to see if that's a YAML, otherwise its a JSON. 😂😂😂😂😂 I'm dead... 😂😂😂

I also realized that probably this project cannot do anything with it, so I'm closing the issue. Sorry to report it to the wrong place.
